[package]
name = "travelers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.23.0", features = ["full"] }
stun_codec = "0.2"
bytecodec = "0.4"
port_scanner = "0.1"